### ISSUE TITLE
Add: CompilerWorks

### ISSUE THREAD

**Issue by geraldcw** [mgaudet/CompilerJobs#29]
Company: http://www.compilerworks.com
Jobs: http://www.compilerworks.com/about.html#jobs

📤: Remote work supported
🗺: Various [map ](https://www.google.com/maps/d/u/0/viewer?mid=1QWGEbJNna8TipgJZpYRYqCUNDsj3cqzT&ll=-3.81666561775622e-14%2C-9.286491447135973&z=1)
Wide range of SQL and "supporting" language compilers (and transpilers.)

**Comment by mgaudet** [comment]
Done in cf3bbb1593175a028035026794a3ae5c9473f116,

Thanks again!
