### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by mgaudet** [mgaudet/CompilerJobs#8]
Who is building things like 

* OCaml
* ML
* Haskell?

(Thanks to @PaulBone for the reminder of an entire subfield I forgot)

**Comment by oneturkmen** [comment]
[Jane Street](https://blog.janestreet.com/work-on-the-ocaml-compiler-at-jane-street/)?

**Comment by mgaudet** [comment]
Adding them! Thanks for the great reminder!

**Comment by PaulBone** [comment]
No worries. I put the ones I knew about. But this exercise made me realise just how little commercial support there are for these projects.  I suppose MSR is commercial, indirectly.

**Comment by typesanitizer** [comment]
We can probably close this, I think all the major functional languages which have dedicated teams at one or more companies are covered now.
