### ISSUE TITLE
Harvest this HN post for ideas

### ISSUE THREAD

**Issue by mgaudet** [mgaudet/CompilerJobs#91]
https://news.ycombinator.com/item?id=32610780 

Chip Startups could need compilers!

**Comment by vmiheer** [comment]
Don't graphcore/cerebras/groc qualify for this? Or you are thinking of some other chips? Or compilers for hardware synthesis languages like bluespec?

**Comment by mgaudet** [comment]
HDL/Synthesis compilers are definitely in scope: never heard of blue spec, but if you could add them that would certainly be great if they apply.
