### ISSUE TITLE
Open jobs or active compiler teams?

### ISSUE THREAD

**Issue by seibert** [mgaudet/CompilerJobs#93]
At Anaconda, we no longer have any currently open compiler positions, but we do have an active compiler team still.  Should I open a PR to remove Anaconda from the list, or is this list also for showing which companies have compiler teams?  (We are likely to hire again in the future, but no ETA on that.)

**Comment by mgaudet** [comment]
This is to list companies who have compilers teams; one day I'd love to collect postings, but that would be far too high overhead for me at the moment. 

See https://www.mgaudet.ca/technical/2019/12/10/compiler-jobs for the motivation.
